### ISSUE TITLE
cardflight.isAttached always true after disconnected

### ISSUE THREAD

**Issue by damrbaby** [loganthompson/cordova-cardflight#2]
Once `CFATTACHED` is set to true, it does not get set to false if the reader is disconnected.

Also, which should we be using? Attached or connected and what is the difference between the two?  Thanks!

**Comment by loganthompson** [comment]
Hey!

isConnected is (was) much more reliable. It should have been called out. However, now isAttached has been updated and should reflect accurately.

The difference is based on the CardFlight SDK's differences between a reader 'attaching' and 'connecting'. Attached is just a physical attachment, whereas a connection means the reader is getting a signal and is actually connected via wifi/data, etc.

Thanks for the note and please update to see this fix!
